services:
  postgres:
    image: postgres:16
    container_name: payment-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password

    ports:
      - "55432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: